name: festim-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib
  - meshio[all]
  - numpy==1.24
  - pip>=20.1
  - ipykernel
  - nbconvert
  - mpi4py<4
  - mshr
  - pip:
    - festim~=1.3
    - pyparsing
    - h-transport-materials==0.16
