name: festim-workshop
channels:
  - conda-forge
  - defaults
dependencies:
  - fenics
  - matplotlib==3.7.1
  - meshio[all]
  - numpy==1.24
  - pip>=20.1
  - ipykernel
  - nbconvert
  - pip:
    - festim==1.3
    - pyparsing
    - h-transport-materials==0.16