# This is a basic workflow to help you get started with Actions

name: Test demos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - dev
  pull_request:

# defaults:
#   run:
#     # ensure base env is activated when running commands
#     shell: bash -eo pipefail -c "source /opt/conda/etc/profile.d/conda.sh; conda activate base; source {0}"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ""

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install dependencies
        run : |
          conda install -c conda-forge mamba
          mamba install -c conda-forge fenics
          pip install -r requirements.txt
          pip install nbconvert

      - name: Run Task 1
        run: |
          cd tasks
          jupyter-nbconvert --to python task1.ipynb
          python task1.py
      - name: Run Task 2
        run: |
          cd tasks
          jupyter-nbconvert --to python task2.ipynb
          python task2.py
      - name: Run Task 3
        run: |
          cd tasks
          jupyter-nbconvert --to python task3.ipynb
          python task3.py
      - name: Run Task 4
        run: |
          cd tasks
          jupyter-nbconvert --to python task4.ipynb
          python task4.py
      - name: Run Task 5
        run: |
          cd tasks
          jupyter-nbconvert --to python task5.ipynb
          python task5.py
      - name: Run Task 6
        run: |
          cd tasks
          jupyter-nbconvert --to python task6.ipynb
          python task6.py
      - name: Run Task 7
        run: |
          cd tasks
          jupyter-nbconvert --to python task7.ipynb
          python task7.py
      - name: Run Task 8
        run: |
          cd tasks
          jupyter-nbconvert --to python task8.ipynb
          python task8.py
