# This is a basic workflow to help you get started with Actions

name: Test demos

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
    - main
    - dev
  pull_request:
  schedule:
    # runs every day at 00:00 UTC
    - cron:  '0 0 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: festim-workshop
          miniforge-version: latest
          environment-file: environment.yml
          use-mamba: true
          channels: conda-forge

      - name: Run Task 1
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task1.ipynb
          conda run python task1.py

      - name: Run Task 2
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task2.ipynb
          conda run python task2.py
      - name: Run Task 3
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task3.ipynb
          conda run python task3.py
      - name: Run Task 4
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task4.ipynb
          conda run python task4.py
      - name: Run Task 5
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task5.ipynb
          conda run python task5.py
      - name: Run Task 6
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task6.ipynb
          conda run python task6.py
      - name: Run Task 7
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task7.ipynb
          conda run python task7.py
      - name: Run Task 8
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task8.ipynb
          conda run python task8.py
      - name: Run Task 9
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task9.ipynb
          conda run python task9.py
      - name: Run Task 10
        shell: bash -l {0}
        run: |
          cd tasks
          jupyter-nbconvert --to python task10.ipynb
          conda run python task10.py